// EXPORT FUNCTION WITH STATE AND ACTION ARGUMENTS
// REDUCERS ARE ONLY CALLED WHEN AN ACTION OCCERS, SO YOU WILL HAVE THAT ARGUMENT
// THE STATE ARGUMENT IS NOT APPLICATION STATE, ONLY THE STATE THIS REDUCER IS RESPONIBLE FOR
export default function(state = null, action) {
	// SWITCH STATEMENT TO CHECK ACTION TYPE
	switch(action.type) {
		case 'BOOK_SELECTED':
			return action.payload;
	}

	return state;
}